#!/bin/bash

source .fonctions

CLEAN_SETUP () {
  echo ""
}
TRAP_ON

app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN
is_public=$YNH_APP_ARG_IS_PUBLIC
language=$YNH_APP_ARG_LANGUAGE
port=8001

sudo yunohost app setting $app domain -v $domain
sudo yunohost app setting $app path -v $path
sudo yunohost app setting $app admin -v $admin
sudo yunohost app setting $app is_public -v $is_public
sudo yunohost app setting $app language -v $language

# Source app helpers
source /usr/share/yunohost/helpers

CHECK_VAR "$app" "app name not set"

CHECK_USER "$admin"

CHECK_PATH
CHECK_DOMAINPATH

CHECK_FINALPATH

FIND_PORT "$port"

# Install dependencies
sudo apt-get install -y curl openssh-server ca-certificates postfix apt-transport-https
curl https://packages.gitlab.com/gpg.key | sudo apt-key add -

# Add gitlab package and install it
sudo curl -sS https://packages.gitlab.com/install/repositories/gitlab/raspberry-pi2/script.deb.sh | sudo bash
sudo apt-get install -y gitlab-ce

# Configure gitlab
sed -i "s@GENERATED_EXTERNAL_URL@https://$domain@g" ../conf/gitlab.rb
sed -i "s@PORT@$port@g" ../conf/gitlab.rb
sudo cp -f ../conf/gitlab.rb /etc/gitlab/gitlab.rb
sudo gitlab-ctl reconfigure

# Configure nginx
sed -i "s@PORT@$port@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/gitlab.conf

# Set public
if [ "$is_public" = "Yes" ];
then
	sudo yunohost app setting gitlab skipped_uris -v "/"
  sudo yunohost app setting gitlab protected_uris -v "/ynhpanel.js,/ynhpanel.json,/ynhpanel.css,/yunohost/sso"
fi

# Reload Nginx, restart seafile and regenerate SSOwat conf
sudo yunohost app ssowatconf
sudo service nginx reload
sudo gitlab-ctl restart

